In [1]:
a = 3
print(type(a))

a = "Hello"
print(type(a))

<class 'int'>
<class 'str'>


In [2]:
pi = 3.14159265358979323846
print(f"The value of pi is: {pi:0.4f}.")

The value of pi is: 3.1416.


In [3]:
# Create a tuple
t = 1, True, "Hello"
print(t)
print(type(t))

# And a List
l = [2.3, 1, 0, -2]
print(l)
print(type(l))

(1, True, 'Hello')
<class 'tuple'>
[2.3, 1, 0, -2]
<class 'list'>


In [4]:
# Define a list and a tuple
l = [2.3, 1, 0, -2]
t = (1, True, "Hello", -1)

# Access its element of index 2
print(l[2])
print(t[2])

# Modify the element
l[2] = 1.1
t[2] = 1.1

0
Hello


TypeError: 'tuple' object does not support item assignment

In [5]:
# Define a list
l = [1, 3, 2, 4, 1, 6, 3, 9]
print(l[2:4])
print(l[::-1])

[2, 4]
[9, 3, 6, 1, 4, 2, 3, 1]


In [6]:
# Printing numbers from 0 to 4 (i.e. 5 - 1)
l = ["a", True, 1]

for i in l: # when a single value is specified -> start = 0, step = 1.
    print(i, i*2)

a aa
True 2
1 2


In [7]:
# Load into memory a few packages
import math
import random

# Print the exponential of a random number in the range (0, 1)
x = random.random() # Random number in the range (0, 1)
print(math.exp(x)) # Exponential of that number

1.3555057952355718


In [8]:
import random as rnd

x = rnd.random()
print(x)

0.48048541650096344


In [9]:
from random import *
print(random())

0.569419486860567


In [10]:
import os

print(os.getcwd())

/Users/davideevangelista/statistical-mathematical-methods/code


In [11]:
relative_path_file = "./data"
absolute_path_file = "/Users/davideevangelista/Desktop/data"

In [12]:
print(os.listdir(absolute_path_file))

FileNotFoundError: [Errno 2] No such file or directory: '/Users/davideevangelista/Desktop/data'

In [13]:
import time
import random

# Initialize a random array of length 100_000
l = [random.gauss() for _ in range(10_000_000)]

# Start timer
start_time = time.time()

# Cycle on l and project to 0 all the negative elements
for i in range(len(l)):
    if l[i] < 0:
        l[i] = 0

# End timer
end_time = time.time()

# Print execution time
print(end_time - start_time)

0.44862985610961914


In [14]:
import numpy as np

# Define a Python list
a = [1, 2, 3]

# Convert it to numpy array
a_vec = np.array(a)

# Check the type of a_vec
print(type(a_vec))
print(a_vec.shape)

<class 'numpy.ndarray'>
(3,)


In [15]:
A = [[1, 1, -1], 
     [2, 0, 0], 
     [0, 1, 2]]
A = np.array(A)

print(A.shape) # Use .shape to print the shape

(3, 3)


In [16]:
a = np.array([1, 2, 3])
print(a.shape)

a_row = np.array([[1, 2, 3]])
print(a_row.shape)

a_col = np.array([[1], [2], [3]])
print(a_col.shape)

(3,)
(1, 3)
(3, 1)


In [17]:
v = np.linspace(0, 1, 11)
print(v)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [18]:
z = np.zeros((5,))
print(z)

[0. 0. 0. 0. 0.]


In [19]:
A = [[1, 1, -1], 
     [2, 0, 0], 
     [0, 1, 2]]
A = np.array(A)
v = np.array([1, 0, 1])
w = np.array([-1, 1, -2])
print(A @ v)

[0 2 2]


In [20]:
import numpy as np
import math
import random
import time

v_np = np.random.normal(0, 1, (10_000_000,))
v = [random.gauss(0, 1) for _ in range(10_000_000)]

start_time = time.time()
y_np = np.exp(v_np)
end_time = time.time()
print(end_time - start_time)

start_time = time.time()
y = [0] * len(v)
for i in range(len(v)):
    y[i] = math.exp(v[i])
end_time = time.time()
print(end_time - start_time)

0.054826974868774414


0.5910859107971191


In [21]:
# Create arrays
v = np.array([0, 1, -1, 2, 1, -1])
w = np.array([0, 0, -1, 1, 2, -1])

# Slicing
t = v[v == w]
print(v)
print(w)
print(t)

[ 0  1 -1  2  1 -1]
[ 0  0 -1  1  2 -1]
[ 0 -1 -1]


In [22]:
v = np.random.normal(0, 1, (10_000_000))
start_time = time.time()
v[v<0] = 0
end_time = time.time()
print(end_time - start_time)

0.03427886962890625
