In [1]:
import numpy as np

# Define a Python list
a = [1, 2, 3]

# Convert it to numpy array
a_vec = np.array(a)

# Check the type of a_vec
print(type(a_vec))

<class 'numpy.ndarray'>


In [2]:
A = [[1, 1, -1], [2, 0, 0], [0, 1, 2]]
A = np.array(A)

print(A.shape) # Use .shape to print the shape

(3, 3)


In [3]:
# Create the vector
a = np.arange(0, 20, 2)

# Visualize the vector
print(a)

[ 0  2  4  6  8 10 12 14 16 18]


In [4]:
import numpy as np

# Dimension of the problem
n = 10

# Create the vectors
x1 = np.linspace(0, 1, n)
x2 = np.random.randn(n)

# Create the matrix
A = np.random.randn(n, n)

# Compute y1 and y2
y1 = A @ x1
y2 = A @ x2

# Compute y = A(x1 + x2)
y = A @ (x1 + x2)

# Check the equality
print(y)
print(y1 + y2)

[-1.22409135 -1.75358188 -1.53887309 -1.78084788  6.76688315 -0.2735545
 -0.04995301 -2.15895619  1.00396131 -0.80654089]
[-1.22409135 -1.75358188 -1.53887309 -1.78084788  6.76688315 -0.2735545
 -0.04995301 -2.15895619  1.00396131 -0.80654089]


In [5]:
# Create the array
v = np.array([0, 1, -1, 2, 1, -1])
print(v)

# Slicing
w = v[0:3]
print(w)

[ 0  1 -1  2  1 -1]
[ 0  1 -1]


In [6]:
# Create the array
v = np.array([0, 1, -1, 2, 1, -1])

# Slicing
idx = np.arange(0, len(v), 2)
w = v[idx]

In [7]:
# Create arrays
v = np.array([0, 1, -1, 2, 1, -1])
w = np.array([0, 0, -1, 1, 2, -1])

# Slicing
t = v[v == w]
print(v)
print(w)
print(t)

[ 0  1 -1  2  1 -1]
[ 0  0 -1  1  2 -1]
[ 0 -1 -1]


In [8]:
# Create the matrix
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Slicing
B = A[:2, :2]

In [9]:
import pandas as pd

# Read data from a csv file
data = pd.read_csv('./data/US_births_2000-2014_SSA.csv')

In [10]:
import numpy as np

# Cast into numpy array
np_data = np.array(data)

# Check that the dimension didn't change
print(f"{data.shape} should be equal to {np_data.shape}")

(5479, 5) should be equal to (5479, 5)
